name: CI/CD Pipeline for Snowflake Native App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SnowSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y snowsql

    - name: Deploy UDFs and Procedures to Snowflake
      env:
        SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
        SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
        SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}
        SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
        SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
      run: |
        snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -q "PUT file://src/udf/*.sql @~/udfs/;"
        snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -q "PUT file://src/procedures/*.sql @~/procedures/;"

    - name: Deploy Streamlit App to Snowflake
      env:
        SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
      run: |
        snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -q "PUT file://src/streamlit/app.py @~/streamlit/;"
        snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -q "CALL SYSTEM$RUN_TASK('streamlit_task');"

